remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Nartay's Personal Website"
description: "A showcase of my publications and projects."
url: "https://nartayaikyn.github.io"
author: Nartay Aikyn

# Personal Details
email: "nartay990531@gmail.com"
phone: "+7-778-541-2333"
location: "Astana, Kazakhstan"

# Social Links
social_links:
  - title: "GitHub"
    url: "https://github.com/NartayAikyn"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/nartay-aikyn/"

# Navigation Links
nav:
  - title: "Home"
    url: "/"

# Include profile photo
profile_picture: "/assets/images/profile.jpg"
