remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Nartay's Personal Website"
description: "test 1 A showcase of my publications and projects."
url: "https://nartayaikyn.github.io"
author: Nartay Aikyn

# Personal Details
email: "nartay990531@gmail.com"
phone: "+7-778-541-2333"
location: "Astana, Kazakhstan"

# Education
education:
  - degree: "MSc in Data Science"
    institution: "Nazarbayev University"
    dates: "August 2022 — June 2024"
    gpa: "3.59 / 4.0"
    thesis: "An Exploration of Video Transformers for Few-Shot Action Recognition"
  - degree: "BS in Computer Science"
    institution: "Nazarbayev University"
    dates: "September 2017 — June 2022"
    gpa: "3.71 / 4.0"

# Research Interests and Experience
research_experience:
  - position: "Research Assistant"
    institution: "Nazarbayev University"
    dates: "July 2022 — Present"
    project: "Edge-assisted activity recognition using skeletal representation and deep learning for video surveillance."
    focus: "Deep Learning, Computer Vision, Few-Shot Learning"
    
# Publications
publications:
  - title: "Efficient facial expression recognition framework based on edge computing"
    journal: "The Journal of Supercomputing"
    year: 2024
    link: "https://example.com/paper1"
  - title: "Few-shot Action Recognition with Video Transformer"
    conference: "2023 17th International Conference on Signal-Image Technology & Internet-Based Systems (SITIS)"
    year: 2023
    link: "https://example.com/paper2"
  - title: "FedFSLAR: A Federated Learning Framework for Few-Shot Action Recognition"
    conference: "Proceedings of the IEEE/CVF Winter Conference on Applications of Computer Vision"
    year: 2024
    link: "https://example.com/paper3"

# Honours and Awards
honours:
  - award: "Honorable mention in the International Mathematics Competition"
    year: 2020
  - award: "Third prize in the International Mathematics Competition"
    year: 2019
  - award: "Gold medal in the SIAM Mathematics Olympics competition"
    year: 2019

# Skills
skills:
  languages:
    - English (Proficient, IELTS band 7.5)
    - Kazakh (Native)
    - Chinese (Native)
    - Russian (Intermediate)
  programming_languages:
    - Python
    - Java
    - C++
    - C
    - C#
    - Lua
    - Prolog
    - Javascript
  python_libraries:
    - NumPy
    - Pandas
    - SciKit-Learn
    - OpenCV
    - Keras
    - PyTorch
    - Matplotlib
  other_skills:
    - MySQL
    - HTML/CSS
    - Windows
    - Linux
    - MS Office
    - Google Drive
